# fly.toml app configuration file generated for full-stack-open-pokedex-ancient-forest-3411 on 2024-08-03T16:45:59+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'full-stack-open-pokedex-ancient-forest-3411'
primary_region = 'ams'

[processes]
  app = "node app.js"

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

#  [[http_service.checks]]
#    grace_period = "15s" # grace period does not work
#    interval = "60s"
#    method = "GET"
#    timeout = "10s"
#    path = "/version"

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1

#[deploy]
#  strategy = "canary"

